(() => {
const FNAE = window.FNAE;
const byId = (id) => document.getElementById(id);

FNAE.elements = {
    images: {
        office: byId("office"),
        cameraImage: byId("cameraImage"),
        staticEl: byId("static"),
        errOverlay: byId("errOverlay"),
        camClock: byId("camClock"),
        jumpscareImage: byId("jumpscareImage"),
        deathStaticImage: byId("deathStaticImage")
    },
    audio: {
        fanSound: byId("fanSound"),
        monitorStatic: byId("monitorStatic"),
        buttonClick: byId("buttonClick"),
        powerOutAudio: byId("powerOutAudio"),
        beepSound: byId("beepSound"),
        alarmSound: byId("alarmSound"),
        activateSound: byId("activateSound"),
        damageSound: byId("damageSound"),
        jumpscareSound: byId("jumpscareSound"),
        static3Sound: byId("static3Sound"),
        cameraPanSound: byId("cameraPanSound"),
        overSound: byId("overSound"),
        phonecall1Sound: byId("phonecall1Sound"),
        phonecall2Sound: byId("phonecall2Sound"),
        phonecall3Sound: byId("phonecall3Sound"),
        phonecall4Sound: byId("phonecall4Sound"),
        phonecall5Sound: byId("phonecall5Sound"),
        phonecall6Sound: byId("phonecall6Sound"),
        alarendgSound: byId("alarendgSound"),
        static4Sound: byId("static4Sound")
    },
    hud: byId("hud"),
    cameraWindow: byId("cameraWindow"),
    taskBar: byId("taskBar"),
    camBarTop: byId("camBarTop"),
    camBarBottom: byId("camBarBottom"),
    powerDisplay: byId("power"),
    powerBars: [byId("bar1"), byId("bar2"), byId("bar3"), byId("bar4")],
    camHealthText: byId("camHealthText"),
    controlTab: byId("controlTab"),
    camTab: byId("camTab"),
    lightTab: byId("lightTab"),
    controlPanel: byId("controlPanel"),
    restartBtn: byId("restartBtn"),
    shutVentsBtn: byId("shutVentsBtn"),
    lureBtn: byId("lureBtn"),
    startPopup: byId("startPopup"),
    startButton: byId("startButton"),
    escapeMenu: byId("escapeMenu"),
    quitGameBtn: byId("quitGameBtn"),
    jumpscareContainer: byId("jumpscareContainer"),
    deathStatic: byId("deathStatic"),
    deathContinue: byId("deathContinue"),
    gameOverText: byId("gameOverText"),
    nightDisplay: byId("nightDisplay"),
    decryptWindow: byId("decryptWindow"),
    decryptTitleBar: byId("decryptTitleBar"),
    decryptBtn: byId("decryptBtn"),
    finishBtn: byId("finishBtn"),
    muteBtn: byId("muteBtn"),
    redGradient: byId("redGradientOverlay"),
    endingBlackOverlay: byId("endingBlackOverlay"),
    sleepScreen: byId("sleepScreen"),
    sleepPrompt: byId("sleepPrompt"),
    wakeScreen: byId("wakeScreen"),
    finalScreen: byId("finalScreen"),
    nightSkipPopup: byId("nightSkipPopup"),
    skipNightInput: byId("skipNightInput"),
    skipConfirmBtn: byId("skipConfirmBtn"),
    skipCancelBtn: byId("skipCancelBtn"),
    cameraButtons: [...document.querySelectorAll("[data-camera]")]
};
})();
